FUENTES=alumno.cc borraralumno-1.cc buscarAlumno.cc cargaprofesor.cc cargarcopia.cc credencial.cc exportardatos.cc funcionesordenar.cc guardarcopia.cc importardatos.cc introducirAlumno.cc login.cc main.cc menu.cc modificaralumno.cc mostraralumno.cc mostraralumnos.cc mostrarequipo.cc ordenarAlf.cc profesor.cc registrarprofesor.cc

OBJETOS=alumno.o borraralumno-1.o buscarAlumno.o cargaprofesor.o cargarcopia.o credencial.o exportardatos.o funcionesordenar.o guardarcopia.o importardatos.o introducirAlumno.o login.o main.o menu.o modificaralumno.o mostraralumno.o mostraralumnos.o mostrarequipo.o ordenarAlf.o profesor.o registrarprofesor.o

objeto_final: $(OBJETOS)
	g++ $(OBJETOS) -o final

fuentes_objeto: $(FUENTES)
	g++ -c $(FUENTES)
